version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: web
    restart: always
    volumes:
      - ./src:/src
      - /src/node_modules
      - /src/.next
    ports:
      - 3000:3000
